### ISSUE TITLE
DailyRotateFile will write to the old file if it's been deleted

### ISSUE THREAD

**Issue by mattberther** [winstonjs/winston-daily-rotate-file#18]
> Originally reported by @cheolgook at https://github.com/winstonjs/winston/issues/504

We're using DailyRotateFile transport and also have separate log archiving box. So after a few days, we move all the log files from app boxes to archive server to free up some space on app boxes, and here comes the problem.

So we have log files with very low traffic (like severe errors) that would have only couple of log entries per week, and the node.js app is running for months without restarting.

The app logged something to the file "20141125.log" which is a week ago, and the app is still running, that file "20141125.log" is already moved to the archive days ago, but the app is still pointing to that file. And today, the app is trying to log something more, and it'll write that log message to the old file "20141125.log" rather than "20141202.log". So it actually creates a file named "20141125.log" again and writes log entry in there.

**Comment by N0N4M3pl** [comment]
I have same problem:
after few days without output to log, next output is written to file with old date in filename.

**Comment by johnmcilwain** [comment]
I don't have a fix, but maybe a work around is to (daily) log a '# comment line' that will be ignored by your log processor...that way the rotate function will get called daily at a minimum...just a thought...

**Comment by N0N4M3pl** [comment]
@johnmcilwain Thanks for your advise.
I find solution for my problem: in my nodejs server I used 5 loggers - some of them are constantly used, other not. So my sollution was use only one logger: "**one logger to rule them all**". In my project this way is acceptable.

**Comment by mattberther** [comment]
If anyone has some code examples to demonstrate the problem, they'd be appreciated. The following code creates a new log file every minute with the expected entry in the corresponding file:

```
var winston = require('winston');
require('winston-daily-rotate-file');

var transport = new winston.transports.DailyRotateFile({
  filename: './log',
  datePattern: 'yyyy-MM-dd-HH-mm.',
  prepend: true,
  level: process.env.ENV === 'development' ? 'debug' : 'info'
});

var logger = new (winston.Logger)({
  transports: [
    transport
  ]
});

setInterval(function() {
  logger.info('Test log message');
}, 30*1000);
```

**Comment by johnmcilwain** [comment]
I am not OP, but I did take your script and test with a few diff values and it worked as expected.

**Comment by mattberther** [comment]
Im going to close this as unreproducible given the code sample I posted. If you do have code that can repro this, please re-open the issue. Thanks!

**Comment by rjsaran** [comment]
@mattberther 
We are facing the same issue: Below are the steps to reproduce it.

1. Run following code.
 ```
  var winston = require('winston');
require('winston-daily-rotate-file');

var transport = new winston.transports.DailyRotateFile({
  filename: 'test',
  datePattern: '.yyyy-MM-dd-HH-mm.log',
  localTime: true,
  timestamp: new Date(),
  level: process.env.ENV === 'development' ? 'debug' : 'info'
});

var logger = new (winston.Logger)({
  transports: [
    transport
  ]
});

setInterval(function() {
  logger.info('Test log message');
}, 10 * 1000);

```

2. Delete the file in which the logger is logging when the logger is going to switch the log file.

**Comment by mattberther** [comment]
This should be resolved with #66.

**Comment by rjsaran** [comment]
@mattberther , @shashankbaluni Thanks

**Comment by chak774** [comment]
I still have the same problem. The logger is trying to write to archived log file. Below are the example of how I use the logger:

**logger.js** 

const init = () => {

    //Create Log Directory First
    const logDir = process.env.LOG_DIR_PATH; // directory path you want to set
    if ( !fs.existsSync( logDir ) ) {
        // Create the directory if it does not exist
        console.log("Log directory does not existed. Created Log Directory: ", logDir);
        fs.mkdirSync( logDir );
    }

    //Create Logger
    logger = new (winston.Logger)({
        level: 'info',
        transports: [
            new winston.transports.Console({
                timestamp: () => {return getNowString();},
                formatter: (options) => {return logFormatter(options)}
            }),
            new dailyRotateFile({
              name: 'combined-file',
              timestamp: () => {return getNowString();},
              formatter: (options) => {return logFormatter(options)},
              filename: logDir + 'combined.log',
              datePattern: 'yyyy-MM-dd.',
              prepend: true,
              level: 'info',
              zippedArchive: true
            }),
            new dailyRotateFile({
                name: 'error-file',
                timestamp: () => {return getNowString();},
                formatter: (options) => {return logFormatter(options)},
                filename: logDir + 'error.log',
                datePattern: 'yyyy-MM-dd.',
                prepend: true,
                level: 'error',
                zippedArchive: true
            })
        ]
`module.exports = {
    get : () => logger,
    init : () => init(),
};
`




--------------------------------------------------------
**index.js**

//Initilize a Logger
const logger = require('./util//logger/logger').init();

--------------------------------------------------------

**Other JS which file to use the logger:**

const logger = require('../util//logger/logger').get();
 logger.info('...')

--------------------------------------------------------

**Comment by shikhagupta2611** [comment]
const {
    createLogger,
    transports,
    format
} = require("winston");
require('winston-daily-rotate-file');
const path = require("path")

const transport = new transports.DailyRotateFile({
    filename: path.join(__dirname, "./logs/my.log", "./logs/my-%DATE%.log"),
    datePattern: "YYYY-MM-DD-HH",
    maxSize: "2k",
    maxFiles: "30d" // keep logs for 30 days
});


const logger = createLogger({ //A winston logger is created with the createLogger function. In addition, there is a default logger if no logger is explicitly specified.

    transports: [
        new transports.File({
            filename: "./logs/my.log",
            maxSize: "2k",
            handleRejections: true, 
            handleExceptions: true,
            level: "info", //maximum level of log messages to log
            format: format.combine(
                format.timestamp(),
                format.simple(),
            ),
        }),
        transport
    ],
    exitOnError: false, //By default, winston will exit after logging an uncaughtException so set exitOnError = false to avoid this behaviour

});

module.exports = logger;


Can anyone tell me if i am creating a file my.log then how to rotate this file in another file named as my-%DATE%.log
